### ISSUE TITLE
Test CommitETH

### ISSUE THREAD

**Issue by esques** [rolandkofler/blocktime#1]
try that

**Comment by commiteth** [comment]
Current balance: 1.23400000
Contract address: 0xf24494d8eb60adf2e4bdabedecbb23d058620689
![QR Code](https://commiteth.com/qr/rolandkofler/blocktime/bounty/1/a15b322af1af3ba92ed3f01b4e44c881670a8e0ba583a560bf4c1a9c862b436b/qr.png)
Network: Testnet
To claim this bounty sign up at [https://commiteth.com](https://commiteth.com)
